name: VitePress Deploy to Branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"

      # 3. 安装依赖并构建
      - name: Install and Build
        run: |
          npm install
          npm run docs:build  # 使用你的自定义构建命令

      # 4. 准备部署文件
      - name: Prepare deployment
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          cd docs/.vitepress/dist  # 根据你的项目结构调整路径
          zip -r ../../../dist-content.zip ./*

      # 4. 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          publish_branch: gh-pages
          force_orphan: true
          cname: "" # 如果有自定义域名，请填写在这里
